### ISSUE TITLE
Can you add a license?

### ISSUE THREAD

**Issue by chad3814** [v0Ch/vfk-001#2]
I think it's okay for me to modify, but I'd like to be certain

**Comment by v0Ch** [comment]
Ok. I add lic.  I'm not against modifications. I'm interested in what you want to change:)

**Comment by chad3814** [comment]
Thanks, I'm not smart enough for a 36 key, I'd like to see it with another row

**Comment by v0Ch** [comment]
if you add 6 columns, you will have to use hovering hands or wrist rests. Two years ago I switched from 42 to 36. Now I can type on a 45 degree arс without taking my wrists off the table. Now it seems very convenient.
